"use client";

import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import * as openpgp from "openpgp";

import { useKeyStore } from "./keyStore";
import { api } from "@/lib/api";

/**
 * Per-channel AES key store. Each E2EE channel has a
 * symmetric AES-256-GCM key that's shared between all
 * members. The key is generated by whichever member
 * triggers a rotation, then wrapped with each member's
 * PGP public key for transport through the server.
 *
 * The *unwrapped* AES key is what's held in this store
 * — only ever in volatile RAM, never on disk. When the
 * tab closes / the user signs out, the React state goes
 * away and the GC eventually collects the underlying
 * <c>CryptoKey</c> object.
 *
 * What lives here, per channel:
 * <list type="bullet">
 *   <item><c>key</c>: the raw AES key, ready to use
 *         for encrypt / decrypt.</item>
///   <item><c>version</c>: the channel-side
///         <c>KeyVersion</c> this key corresponds to.
///         Used as the AAD for AES-GCM so a key swap
///         can't accidentally cross-decrypt messages
///         from a previous rotation window.</item>
/// </list>
 *
 * The store also exposes a one-shot "ensure this channel
 * is unlocked" helper that drives the full join flow:
 * fetch the wrapped key from the server, unwrap with
 * the user's PGP private key (from <c>keyStore</c>),
 * cache the result. The MessageList calls this on
 * mount; the RotationWatcher calls it after a
 * successful rotation to swap the new key in.
 */

export interface StoredChannelKey {
  /** The raw AES key. <c>crypto.subtle</c> object —
   *  non-extractable would be safer but we need to
   *  export it on rotation to re-wrap, so it's
   *  extractable. (Phase 3+ can revisit with
   *  <c>deriveKey</c> + a master-key scheme.) */
  key: CryptoKey;
  /** Channel-side <c>KeyVersion</c> this key is for. */
  version: number;
}

interface ChannelKeyStoreValue {
  /** Per-channel key cache. Missing entries mean
   *  "not yet unlocked"; the consumer should call
   *  <see cref="ensureUnlocked"/> on the channel-id. */
  readonly keys: ReadonlyMap<number, StoredChannelKey>;
  /**
   * Resolve (or fetch + unwrap) the channel key for the
   * given channel id. Idempotent: a re-call on a
   * channel that's already in RAM returns the cached
   * entry without an extra server round-trip.
   *
   * Returns <c>null</c> if the user isn't a member of
   * the channel, the user has no PGP key on file, or
   * the user has a PGP key but the private half isn't
   * unlocked in RAM right now.
   */
  ensureUnlocked: (channelId: number) => Promise<StoredChannelKey | null>;
  /** Replace the cached entry for a channel — used by
   *  the rotation watcher once the new key has been
   *  uploaded and the user has unwrapped it locally. */
  set: (channelId: number, entry: StoredChannelKey) => void;
  /** Drop a channel's key (e.g. on leave). */
  clear: (channelId: number) => void;
  /** Drop everything. Called on sign-out. */
  clearAll: () => void;
}

const Context = createContext<ChannelKeyStoreValue | null>(null);

/**
 * Module-level singleton reference. The provider sets
 * it on mount and clears on unmount; non-React callers
 * (e.g. <c>peerInvite.addMemberToChannel</c>) read
 * through <c>getChannelKeyStoreInstance()</c>. This is
 * the standard pattern for getting React-context state
 * from a function that isn't itself a hook.
 */
let currentInstance: ChannelKeyStoreValue | null = null;
export function getChannelKeyStoreInstance(): ChannelKeyStoreValue | null {
  return currentInstance;
}

/**
 * Provider mounted once near the root of the authenticated
 * app. Children call <c>useChannelKeyStore()</c> to read
 * keys and trigger the unwrap flow.
 */
export function ChannelKeyProvider({ children }: { children: ReactNode }) {
  const [keys, setKeys] = useState<Map<number, StoredChannelKey>>(
    () => new Map(),
  );
  const keyStore = useKeyStore();

  const set = useCallback((channelId: number, entry: StoredChannelKey) => {
    setKeys((prev) => {
      const next = new Map(prev);
      next.set(channelId, entry);
      return next;
    });
  }, []);

  const clear = useCallback((channelId: number) => {
    setKeys((prev) => {
      if (!prev.has(channelId)) return prev;
      const next = new Map(prev);
      next.delete(channelId);
      return next;
    });
  }, []);

  const clearAll = useCallback(() => {
    setKeys(new Map());
  }, []);

  const ensureUnlocked = useCallback(
    async (channelId: number): Promise<StoredChannelKey | null> => {
      const cached = keys.get(channelId);
      if (cached) return cached;

      if (!keyStore.unlocked) return null;
      const privateKey = keyStore.unlocked.privateKey;

      const wrapped = await api.e2ee.getMyKey(channelId);
      const message = await openpgp.readMessage({
        armoredMessage: wrapped.encryptedAesKey,
      });
      const { data: rawAesKey } = await openpgp.decrypt({
        message,
        decryptionKeys: privateKey,
        format: "binary",
      });
      const key = await crypto.subtle.importKey(
        "raw",
        rawAesKey as BufferSource,
        { name: "AES-GCM", length: 256 },
        true,
        ["encrypt", "decrypt"],
      );
      const entry: StoredChannelKey = {
        key,
        version: wrapped.keyVersion,
      };
      set(channelId, entry);
      return entry;
    },
    [keyStore.unlocked, keys, set],
  );

  const value = useMemo<ChannelKeyStoreValue>(
    () => ({ keys, ensureUnlocked, set, clear, clearAll }),
    [keys, ensureUnlocked, set, clear, clearAll],
  );

  // Maintain the module-level singleton so non-React
  // callers can reach the store. The previous
  // instance is overwritten on every render — fine,
  // because React only re-renders when the value
  // reference changes, and a fresh memo gives us a
  // fresh reference.
  currentInstance = value;

  return <Context.Provider value={value}>{children}</Context.Provider>;
}

export function useChannelKeyStore(): ChannelKeyStoreValue {
  const v = useContext(Context);
  if (!v) {
    throw new Error(
      "useChannelKeyStore must be used inside <ChannelKeyProvider>.",
    );
  }
  return v;
}
